### ISSUE TITLE
Segfault when opening control panel in threaded mode

### ISSUE THREAD

**Issue by mothnox** [bobke/Critterding2#1]
OS: Manjaro Linux
Steps to reproduce: After compiling, run Critterding2 threaded (./src/bengine app_critterding_threads). Press F2 to open the control panel.
What happens: 
Critterding2 hangs for several seconds before segfaulting. Two new windows, titled Critterding Control Panel and Engine Qt6, can be seen during this time, though there is nothing in them.
Notes: This also happens when launching via the launcher, even when set to use a single thread.

**Comment by bobke** [comment]
good catch, thank you
this occurred when missing Qwt for graphs and in threaded mode only
